apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ NAME }}
spec:
  selector:
    matchLabels:
      app: {{ NAME }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ NAME }}
    spec:
      containers:
        - name: {{ NAME }}
          image: localhost:5000/cde:{{ NAME }}
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: {{ NAME }}
spec:
  selector:
    app: {{ NAME }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ NAME }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /{{ NAME }}
            backend:
              serviceName: {{ NAME }}
              servicePort: 80
